### ISSUE TITLE
Les accessoires Flexom n'apparaissent pas

### ISSUE THREAD

**Issue by Tonio0774** [rsauget/homebridge-flexom#4]
**Describe The Bug:**
après installation, je ne vois aucun des accessoires présent dans Flexom

**Logs:**

TypeError: form_urlencoded_1.default is not a function
    at axios_1.default.create.transformRequest (/Users/T/.npm/_npx/14098/lib/node_modules/@rsauget/flexom-lib/dist/hemis/hemis.js:78:49)
    at transform (/Users/T/.npm/_npx/14098/lib/node_modules/@rsauget/flexom-lib/node_modules/axios/lib/core/transformData.js:16:12)
    at Object.forEach (/Users/T/.npm/_npx/14098/lib/node_modules/@rsauget/flexom-lib/node_modules/axios/lib/utils.js:247:10)
    at transformData (/Users/T/.npm/_npx/14098/lib/node_modules/@rsauget/flexom-lib/node_modules/axios/lib/core/transformData.js:15:9)
    at dispatchRequest (/Users/T/.npm/_npx/14098/lib/node_modules/@rsauget/flexom-lib/node_modules/axios/lib/core/dispatchRequest.js:30:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Plugin Config:**

{
            "name": "Flexom",
            "email": "",
            "password": "",
            "zones": true,
            "excludeZones": false,
            "excludedZones": [
                {
                    "light": true,
                    "window": true
                }
            ],
            "things": true,
            "platform": "Flexom"
        }
    ],
    "accessories": []
}

**Screenshots:**

**Environment:**

* **Plugin Version**: v2.2.1
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.16.1
* **NPM Version**: v6.14.12
* **Operating System**: macOS

**Comment by rsauget** [comment]
Bonjour @Tonio0774 , peux-tu stp réessayer avec la v2.2.2 du plugin ?

**Comment by Tonio0774** [comment]
Je viens de tester avec la nouvelle version et j'ai toujours aucun accessoire et des erreurs : 
```
UnhandledPromiseRejectionWarning: TypeError: form_urlencoded_1.default is not a function
    at axios_1.default.create.transformRequest (/Users/Tonio/.npm-global/lib/node_modules/@rsauget/homebridge-flexom/node_modules/@rsauget/flexom-lib/src/hemis/hemis.ts:47:23)
    at transform (/Users/Tonio/.npm-global/lib/node_modules/@rsauget/homebridge-flexom/node_modules/axios/lib/core/transformData.js:16:12)
    at Object.forEach (/Users/Tonio/.npm-global/lib/node_modules/@rsauget/homebridge-flexom/node_modules/axios/lib/utils.js:247:10)
    at transformData (/Users/Tonio/.npm-global/lib/node_modules/@rsauget/homebridge-flexom/node_modules/axios/lib/core/transformData.js:15:9)
    at dispatchRequest (/Users/Tonio/.npm-global/lib/node_modules/@rsauget/homebridge-flexom/node_modules/axios/lib/core/dispatchRequest.js:30:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rsauget** [comment]
Ok j'ai trouvé, c'est du à une erreur de l'auteur d'une dépendance que j'utilise (https://github.com/iambumblehead/form-urlencoded/issues/35).
Je pousse une nouvelle version au plus vite.

**Comment by Tonio0774** [comment]
Parfait 😊 super travail ! 
j'attends donc avec impatience cette nouvelle version.

**Comment by Buggzounet** [comment]
Bonjour, 
Pareil pour moi : aucun accessoire pour l'instant.
Merci pour le travail @rsauget !

**Comment by rsauget** [comment]
@Tonio0774 peux-tu stp tester la 2.2.3 ?
@Buggzounet bienvenue ! Peux-tu aussi tester la 2.2.3, en espérant que tu aies le même problème ?

**Comment by Tonio0774** [comment]
@rsauget Je viens de tester, les accessoires apparaissent désormais 😊. la seule chose c'est que je ne vois pas les volets roulants dans aucune pièce de HomeKit.

**Comment by Tonio0774** [comment]
@rsauget autant pour moi, je ne savais pas ou les trouver 😊 
Super travail. 
J'ai hate d'avoir accès a chaque accessoires individuellement mais c'est deja énorme.

**Comment by rsauget** [comment]
@Tonio0774 dans les paramètres de l'accessoire tu peux séparer en 2 vignettes si tu préfères !
Tu aurais quand même besoin d'accéder aux accessoires individuellement ? Tu peux ouvrir une autre issue de type "Feature request" si c'est ça 😉

**Comment by rsauget** [comment]
@Buggzounet je cloture cette issue, si ton problème est différent et pas résolu je te laisse créer une issue séparée stp, avec config logs versions etc. comme indiqué dans le modèle d'issue 🙏

**Comment by Buggzounet** [comment]
Merci @rsauget ! ça fonctionne également pour moi 👍 
Je vois mes accessoires... je n'ai plus qu'à configurer le tout.
Bravo et encore merci :)
